"""Author the Keep's set dressing -- region 4, the last one, §6.5's hall.

RUN IT WITH `--write` OR IT DOES NOTHING. Twice now I have read "resolved 105
placements, all clear" as "written" and gone looking for a rendering bug that did
not exist. The tell is `envSpritesPlaced` in the capture output not moving.

    python3 tools/overworld/place_keep.py               # check only
    python3 tools/overworld/place_keep.py --write       # check, preview, write

WHAT THIS REPLACES. Forty-four placements of `env_hall_*` keys -- and there is no
`assets/sprites/env/hall/` directory and there never was one in this build, so
every one of them was a dead key and the last region of the game has been
shipping with an EMPTY hall. The palette gate, the plate check and `tsc` were all
green through that, because none of them look at whether a texture key resolves.
It took walking the region in a browser capture to find out.

THE FOUR VIGNETTES ARE THE FOUR PAINTED DISTRICTS, which is the whole trick to
making dressing feel like architecture rather than like scatter: `paint_ground.py`
already paints a sodden carpet at (292,62), rows of silted seating at (322,60),
the darkest floor in the game at (336,26), and pale marble at (308,46). Standing
the right furniture on the right floor costs nothing and does more for the read
than any amount of density.

    the-foyer          ~(305,62)  the way in. A door standing open.
    the-stalls          (322,60)  the audience, and it is empty.
    the-orchestra-pit   (336,26)  the players, still on their stands.
    the-marble-approach ~(320,40)  the walk to Lunal. boss_1 is at (308,41).

TWO OF THE FOUR ARE OFF THEIR DISTRICT CENTRES, and the reason is a genuine
disagreement between two systems that both describe this ground. `paint_ground`
paints a sodden carpet centred on (292,62) and pale marble on (308,46); the
TILEMAP says (292,62) is 24% dry and (308,46) is open water. The paint is
cosmetic and the tilemap is authoritative -- it is what the player collides with
-- so the furniture follows the tilemap and sits at the dry edge of each painted
patch instead of its centre. Worth knowing before adding a fifth district: the
plate and the map are generated by different scripts and nothing checks that
they agree about what is floor.

AND THE HALL IS QUIET. §6.5: "an orchestra that drowned mid-performance...
dressing, not characters. Beautiful, and NOBODY'S story." So there is no chaos
anywhere in these 47 placements -- nothing overturned, nothing smashed, nothing
strewn. Instruments on stands, chairs square to their desks, one chair in
`chair_row` turned out and pushed back, and that is the entire amount of
narrative this region is allowed. Everything else is silt and time.

`stopped_clock` IS NEVER FLIPPED. A mirror reverses the hands, and the four
clocks in this hall all reading the same minute is the only thing a clock-keeper
would notice about the place. There is an assertion at the bottom of this file
that fails the build rather than let a flipped one through.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from place_kit import Kit, place  # noqa: E402

# Must match the keep block of WorldScale.METERS. Authored at 32 px per intended
# tile, so `metres == tiles` -- see env_keep.py.
METERS = {
    "proscenium": 6.0,
    "organ_pipes": 5.5,
    "pillar": 5.0,
    "hall_door": 4.0,
    "harp": 3.2,
    "stopped_clock": 3.0,
    "seat_bank": 2.8,
    "candelabra": 2.4,
    "chandelier_down": 2.0,
    "music_stand": 2.0,
    "timpani": 1.9,
    "cello": 1.6,
    "chair_row": 1.6,
    "chair": 1.4,
    "podium": 0.8,
    "sheet_drift": 0.8,
}
# `sheet_drift` IS ALLOWED ON THE ROAD, and it is the only thing in the kit that
# is. Loose paper is what the water moved; it went where the water went, and the
# route through this hall is the low line, so paper on the path is not an
# obstacle, it is the evidence of a current. Everything else stays clear --
# a chandelier across the only way north is just a wall.
KIT = Kit(region_index=4, biome="keep", meters=METERS, road_ok=frozenset({"sheet_drift"}))


# ---------------------------------------------------------------------------
# 1. THE FOYER -- the way in, on the sodden-carpet district at (292,62)
# ---------------------------------------------------------------------------
# The player arrives here off the Scar, which is open sky, dust and dead ground.
# The first thing this region has to do is say INTERIOR: a doorway, a floor with
# a nap to it, columns holding something up. It is also the only vignette with a
# lit piece in it, and the light is at the threshold, so the hall the player is
# looking INTO is darker than the doorway they are standing in.
FOYER = [
    # THE DOOR, STANDING OPEN. §6.5: she "arrived first and found it empty, which
    # is why she chose it." Nobody forced this and nobody barred it.
    place("the-foyer", "hall_door", 305, 63),
    # two columns, unequal distance from the door, because a symmetrical pair
    # framing an entrance is a rendering
    place("the-foyer", "pillar", 299, 62),
    place("the-foyer", "pillar", 311, 61, flip=True),
    # the paper the water pushed into the corners
    place("the-foyer", "sheet_drift", 302, 66),
    place("the-foyer", "sheet_drift", 309, 67, flip=True),
    place("the-foyer", "sheet_drift", 297, 59),
    # two chairs, alone, at odd angles -- somebody carried them out here and left
    # them, and a single chair is the smallest object in the game that implies a
    # person-sized body
    place("the-foyer", "chair", 307, 58),
    place("the-foyer", "chair", 302, 56, flip=True),
    # THE FIRST CLOCK. There are four in this region and they all read 4:51.
    place("the-foyer", "stopped_clock", 313, 58),
    place("the-foyer", "candelabra", 314, 62),
]

# ---------------------------------------------------------------------------
# 2. THE STALLS -- the audience, on the silted-seating district at (322,60)
# ---------------------------------------------------------------------------
# THE MOST IMPORTANT THING IN THIS REGION IS THAT THE SEATS ARE EMPTY. A ruined
# stage says nobody plays here. A ruined auditorium says nobody LISTENED, which
# is worse, and it is the sentence §6.5 wants under Lunal's hall. Four banks of
# seven, staggered, each one a couple of tiles off the last, because rows in a
# real house curve and step.
STALLS = [
    place("the-stalls", "seat_bank", 319, 67),
    place("the-stalls", "seat_bank", 328, 66, flip=True),
    place("the-stalls", "seat_bank", 318, 63),
    place("the-stalls", "seat_bank", 329, 62, flip=True),
    place("the-stalls", "seat_bank", 323, 59),
    # THE CHANDELIER, LOWERED FOR ITS CANDLES AND NEVER RAISED. You winch a
    # chandelier down to service it; somebody did that on an ordinary afternoon.
    # Nothing fell. It is exactly where the work stopped, and that is the whole
    # premise of this world stated without a word.
    place("the-stalls", "chandelier_down", 324, 54),
    # the columns at the side walls
    place("the-stalls", "pillar", 314, 66),
    place("the-stalls", "pillar", 336, 63, flip=True),
    # paper drifted along the foot of the seating
    place("the-stalls", "sheet_drift", 321, 70),
    place("the-stalls", "sheet_drift", 332, 57, flip=True),
    # THE SECOND CLOCK, on the side wall where a latecomer would check it
    place("the-stalls", "stopped_clock", 339, 59),
    place("the-stalls", "chair", 316, 55),
]

# ---------------------------------------------------------------------------
# 3. THE ORCHESTRA PIT -- the players, on the darkest floor in the game (336,26)
# ---------------------------------------------------------------------------
# §6.5's line in full: "an orchestra that drowned mid-performance -- beautiful,
# and NOBODY'S story." Everything in this vignette is on its stand, square, put
# down rather than dropped. The single exception is the fourth chair in
# `chair_row`, turned out and pushed back, which is what a chair looks like when
# somebody stood up, and it is the only narrative beat the region gets.
#
# THE ORGAN IS THE ANCHOR. Five and a half tiles of it at the back of the pit,
# and it is the one piece here tall enough to close the composition -- without it
# the vignette is furniture on a dark floor with nothing behind it.
ORCH_PIT = [
    place("the-orchestra-pit", "organ_pipes", 336, 20),
    # the strings, downstage of the organ
    place("the-orchestra-pit", "harp", 329, 24),
    place("the-orchestra-pit", "cello", 341, 25, flip=True),
    place("the-orchestra-pit", "cello", 326, 29),
    # THE ONLY DRUMS IN A GAME ABOUT RHYTHM, silt-filled and silent. The joke is
    # never pointed out.
    place("the-orchestra-pit", "timpani", 344, 20),
    # the desks: five stands, none of them at the same angle, and every one still
    # has its part open on it. An empty stand is furniture; a stand with music on
    # it is a person who was reading it four bars ago.
    place("the-orchestra-pit", "music_stand", 331, 30),
    place("the-orchestra-pit", "music_stand", 335, 31, flip=True),
    place("the-orchestra-pit", "music_stand", 339, 29),
    place("the-orchestra-pit", "music_stand", 328, 32, flip=True),
    place("the-orchestra-pit", "music_stand", 343, 32),
    # the chairs behind the desks, and one of them is pushed back
    place("the-orchestra-pit", "chair_row", 332, 34),
    place("the-orchestra-pit", "chair_row", 340, 35, flip=True),
    place("the-orchestra-pit", "chair", 346, 28),
    # the riser she stood on. The wear on top is the piece: two dull patches
    # where a pair of feet stood for however many hundred nights.
    place("the-orchestra-pit", "podium", 336, 27),
    place("the-orchestra-pit", "sheet_drift", 333, 17),
    place("the-orchestra-pit", "sheet_drift", 342, 16, flip=True),
    # THE THIRD CLOCK, at the back of the pit. echo_45 is at (335,75) and reads
    # "Every one of them stopped at the same minute."
    place("the-orchestra-pit", "stopped_clock", 347, 24),
]

# ---------------------------------------------------------------------------
# 4. THE MARBLE APPROACH -- the walk to Lunal. boss_1 stands at (308,41).
# ---------------------------------------------------------------------------
# The last stretch of ground in the game, on the one pale floor in five regions.
# It is a COLONNADE, deliberately: the player has spent four regions in open
# country and broken streets, and the final approach is the most formal, most
# expensive, most deliberately composed space they have walked through -- which
# is what makes §7's warm little room land as a relief rather than as a repeat.
#
# THE PROSCENIUM STANDS NORTH OF THE BOSS TILE so the player walks TOWARD it and
# fights under it. Six tiles tall and seven and a half wide, it is the only
# built landmark in the game and it frames the last fight.
MARBLE = [
    place("the-marble-approach", "proscenium", 321, 36),
    # the colonnade: four columns, two a side, and the spacing is uneven on
    # purpose -- an even four is a fence
    place("the-marble-approach", "pillar", 314, 48),
    place("the-marble-approach", "pillar", 329, 47, flip=True),
    place("the-marble-approach", "pillar", 316, 40),
    place("the-marble-approach", "pillar", 328, 39, flip=True),
    # the last two lit things in the game before the warm room
    place("the-marble-approach", "candelabra", 319, 46),
    place("the-marble-approach", "candelabra", 325, 47, flip=True),
    # THE FOURTH CLOCK, and it is the last object the player passes. 4:51 again.
    place("the-marble-approach", "stopped_clock", 332, 43),
    place("the-marble-approach", "sheet_drift", 322, 48),
    place("the-marble-approach", "sheet_drift", 317, 44, flip=True),
    place("the-marble-approach", "chair", 312, 45, flip=True),
]

KEEP = FOYER + STALLS + ORCH_PIT + MARBLE

# THE ASSERTION THAT MATTERS. A mirrored longcase clock reads its own time
# backwards, and the four of them agreeing is the only reason the piece exists.
# This is a build failure, not a warning, because the bug is invisible: a flipped
# clock looks like a clock.
_flipped = [p for p in KEEP if p["piece"] == "stopped_clock" and p.get("flip")]
assert not _flipped, "stopped_clock must never be flipped: %r" % _flipped


if __name__ == "__main__":
    # snap=3 for the same reason the Scar needs it: this region's road was
    # generated, not drawn by hand, so authored tiles land on it by accident.
    raise SystemExit(KIT.main(sys.argv, KEEP, preview_window=(282, 354, 14, 76), snap=6))
