/**
 * SongMap -- the authored beat map of a real recorded track (PRD §8.3).
 *
 * The Inhalants songs are real band recordings, not click-tracked renders, so
 * a constant bpm+offset line does not fit them exactly (measured tempo
 * stability is 84-92% across the six tracks). The full `beatTimesMs` grid --
 * every tracked beat, in milliseconds into the audio file -- is therefore the
 * judgment source of truth; `bpm` and `firstBeatOffsetMs` are the fitted
 * summary (HUD pulse rate, tick pacing, fallback grid).
 *
 * Generated by `tools/audio/measure_beats.py`; re-run it after any track
 * change. PRD §8.3 additionally calls for a human listening pass over the
 * measured grids.
 *
 * Times are file-time: judgment maps the playing element's `currentTime`
 * through this grid, so a changed `playbackRate` (game speed, §8.3.3) can
 * never desynchronize the judged beat from the heard one.
 */
export interface SongMap {
  songId: string;
  /** Fitted global BPM (nominal -- summary of the grid, not the judge). */
  bpm: number;
  /** First tracked beat, ms into the file. */
  firstBeatOffsetMs: number;
  /** File duration in ms; the element loops here, so the grid wraps. */
  durationMs: number;
  /** Every tracked beat, ms into the file, strictly increasing. */
  beatTimesMs: number[];
  /** Named bar-aligned sections (boss phases, §8.7) -- P2, optional. */
  sections?: { name: string; startMs: number }[];
}
